/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    pages: Page;
    presets: Preset;
    media: Media;
    menus: Menu;
    'static-text': StaticText;
    regions: Region;
    cities: City;
    locations: Location;
    'butcher-categories': ButcherCategory;
    'product-categories': ProductCategory;
    careers: Career;
    'career-applications': CareerApplication;
    promotions: Promotion;
    'staff-guidebook-categories': StaffGuidebookCategory;
    'staff-guidebook-pages': StaffGuidebookPage;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    presets: PresetsSelect<false> | PresetsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    'static-text': StaticTextSelect<false> | StaticTextSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'butcher-categories': ButcherCategoriesSelect<false> | ButcherCategoriesSelect<true>;
    'product-categories': ProductCategoriesSelect<false> | ProductCategoriesSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    'career-applications': CareerApplicationsSelect<false> | CareerApplicationsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'staff-guidebook-categories': StaffGuidebookCategoriesSelect<false> | StaffGuidebookCategoriesSelect<true>;
    'staff-guidebook-pages': StaffGuidebookPagesSelect<false> | StaffGuidebookPagesSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'vi' | 'th' | 'tl' | 'cs' | 'sk';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  description?: string | null;
  style?: ('default' | 'dark') | null;
  content: (
    | {
        type?: ('default' | 'multi-link') | null;
        alignment?: ('center' | 'left') | null;
        icon?: (number | null) | Media;
        backgroundImage: number | Media;
        title: string;
        subtitle?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        links?:
          | {
              link: {
                appearance?: ('primary' | 'highlight') | null;
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        basicInfo?: {
          appearance?: ('simple' | 'simple-alt' | 'promo') | null;
          backgroundImage?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
        };
        panels?:
          | {
              image?: (number | null) | Media;
              title: string;
              subtitle?: string | null;
              text: string;
              links?:
                | {
                    link: {
                      appearance?: ('primary' | 'highlight') | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      icon?:
                        | (
                            | 'email'
                            | 'phone'
                            | 'facebook'
                            | 'instagram'
                            | 'whatsapp'
                            | 'zalo'
                            | 'account'
                            | 'reservations'
                            | 'orders'
                            | 'vouchers'
                            | 'billing'
                            | 'notifications'
                            | 'addresses'
                            | 'invoices'
                          )
                        | null;
                      reference?: {
                        relationTo: 'pages';
                        value: number | Page;
                      } | null;
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'multi-panel-cta';
      }
    | {
        basicInfo?: {
          style?: ('default' | 'landing' | 'product-page') | null;
          backgroundImage?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
        };
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        categories?:
          | {
              category?: (number | null) | ButcherCategory;
              columns?: number | null;
              rows?: number | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        footer?:
          | {
              icon: number | Media;
              title: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'butcher-shop-promo';
      }
    | {
        basicInfo?: {
          title?: string | null;
          description?: string | null;
        };
        categories: (number | ProductCategory)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'product-highlights';
      }
    | {
        basicInfo: {
          line1: string;
          line2: string;
        };
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        images?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'social-feed';
      }
    | {
        line1: string;
        line2: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'region-select-header';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'locations-grid';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'cities-filter';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'discover-locations';
      }
    | {
        style?: ('default' | 'alt') | null;
        title?: string | null;
        image?: (number | null) | Media;
        testimonies: {
          image: number | Media;
          name: string;
          testimony: string;
          rating: number;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        title: string;
        text?: string | null;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'page-header';
      }
    | {
        title: string;
        text?: string | null;
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'text-and-image';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'event-room-selector';
      }
    | {
        title: string;
        text: string;
        type?: 'catering' | null;
        targetEmail: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact-request-form';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'promo-list';
      }
    | {
        style?: ('full-grid' | 'embedded') | null;
        title: string;
        subtitle?: string | null;
        description?: string | null;
        bgImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'careers-grid';
      }
    | {
        style?: ('plain' | 'full-width') | null;
        title?: string | null;
        slides?:
          | {
              image: number | Media;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'carousel';
      }
    | {
        title: string;
        subtitle?: string | null;
        style?: ('default' | 'product-page') | null;
        shop?: ('butcher-shop' | 'all-day-dining') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'specials';
      }
    | {
        title: string;
        links?:
          | {
              link: {
                appearance?: ('primary' | 'highlight') | null;
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
    | {
        title: string;
        description: string;
        amount_presets?:
          | {
              region: number | Region;
              disclaimer?: string | null;
              amounts?:
                | {
                    amount: number;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'vouchers';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  description?: string | null;
  vendure_id?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "butcher-categories".
 */
export interface ButcherCategory {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  vendureSlug: string;
  defaultImage: number | Media;
  availableRegions?: (number | Region)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  country_code: string;
  currency_code: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  defaultLocale?: ('en' | 'vi' | 'th' | 'tl' | 'cs' | 'sk') | null;
  availableLocales?: ('en' | 'vi' | 'th' | 'tl' | 'cs' | 'sk')[] | null;
  hostnames: string;
  vendureChannel: string;
  vendureDeliveryChannel: string;
  awsMapProvider?: string | null;
  awsPlacesIndex?: string | null;
  awsLocationRegion?: string | null;
  awsLocationKey?: string | null;
  awsLocationAccessKey?: string | null;
  awsLocationSecret?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories".
 */
export interface ProductCategory {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  vendureSlug: string;
  parentCategory?: (number | null) | ProductCategory;
  defaultImage?: (number | null) | Media;
  availableRegions?: (number | Region)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presets".
 */
export interface Preset {
  id: number;
  name: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  description?: string | null;
  style?: ('default' | 'dark') | null;
  content: (
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'store-product-details';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'location-hero';
      }
    | {
        bgImage: number | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'location-info';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'location-areas';
      }
    | {
        title: string;
        text: string;
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'location-highlight';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'career-details';
      }
    | {
        type?: ('default' | 'multi-link') | null;
        alignment?: ('center' | 'left') | null;
        icon?: (number | null) | Media;
        backgroundImage: number | Media;
        title: string;
        subtitle?: string | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        links?:
          | {
              link: {
                appearance?: ('primary' | 'highlight') | null;
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-hero';
      }
    | {
        basicInfo?: {
          appearance?: ('simple' | 'simple-alt' | 'promo') | null;
          backgroundImage?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
        };
        panels?:
          | {
              image?: (number | null) | Media;
              title: string;
              subtitle?: string | null;
              text: string;
              links?:
                | {
                    link: {
                      appearance?: ('primary' | 'highlight') | null;
                      type?: ('reference' | 'custom') | null;
                      newTab?: boolean | null;
                      icon?:
                        | (
                            | 'email'
                            | 'phone'
                            | 'facebook'
                            | 'instagram'
                            | 'whatsapp'
                            | 'zalo'
                            | 'account'
                            | 'reservations'
                            | 'orders'
                            | 'vouchers'
                            | 'billing'
                            | 'notifications'
                            | 'addresses'
                            | 'invoices'
                          )
                        | null;
                      reference?: {
                        relationTo: 'pages';
                        value: number | Page;
                      } | null;
                      url?: string | null;
                      label: string;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-multi-panel-cta';
      }
    | {
        basicInfo?: {
          style?: ('default' | 'landing' | 'product-page') | null;
          backgroundImage?: (number | null) | Media;
          title?: string | null;
          description?: string | null;
        };
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        categories?:
          | {
              category?: (number | null) | ButcherCategory;
              columns?: number | null;
              rows?: number | null;
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        footer?:
          | {
              icon: number | Media;
              title: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-butcher-shop-promo';
      }
    | {
        basicInfo?: {
          title?: string | null;
          description?: string | null;
        };
        categories: (number | ProductCategory)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-product-highlights';
      }
    | {
        basicInfo: {
          line1: string;
          line2: string;
        };
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        images?:
          | {
              image?: (number | null) | Media;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-social-feed';
      }
    | {
        line1: string;
        line2: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-region-select-header';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-locations-grid';
      }
    | {
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-cities-filter';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-discover-locations';
      }
    | {
        style?: ('default' | 'alt') | null;
        title?: string | null;
        image?: (number | null) | Media;
        testimonies: {
          image: number | Media;
          name: string;
          testimony: string;
          rating: number;
          id?: string | null;
        }[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-testimonials';
      }
    | {
        title: string;
        text?: string | null;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-page-header';
      }
    | {
        title: string;
        text?: string | null;
        images: (number | Media)[];
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-text-and-image';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-event-room-selector';
      }
    | {
        title: string;
        text: string;
        type?: 'catering' | null;
        targetEmail: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-contact-request-form';
      }
    | {
        title: string;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-promo-list';
      }
    | {
        style?: ('full-grid' | 'embedded') | null;
        title: string;
        subtitle?: string | null;
        description?: string | null;
        bgImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-careers-grid';
      }
    | {
        style?: ('plain' | 'full-width') | null;
        title?: string | null;
        slides?:
          | {
              image: number | Media;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-carousel';
      }
    | {
        title: string;
        subtitle?: string | null;
        style?: ('default' | 'product-page') | null;
        shop?: ('butcher-shop' | 'all-day-dining') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-specials';
      }
    | {
        title: string;
        links?:
          | {
              link: {
                appearance?: ('primary' | 'highlight') | null;
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-cta';
      }
    | {
        type?: ('butcher-shop' | 'all-day-dining' | 'gift-cards' | 'merchandise') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-shop';
      }
    | {
        title: string;
        description: string;
        amount_presets?:
          | {
              region: number | Region;
              disclaimer?: string | null;
              amounts?:
                | {
                    amount: number;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'preset-vouchers';
      }
  )[];
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  items?:
    | {
        title: string;
        type?: ('link' | 'submenu' | 'locations' | 'regions') | null;
        style?: ('primary' | 'highlight') | null;
        colspan?: number | null;
        subitems?:
          | {
              title: string;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                icon?:
                  | (
                      | 'email'
                      | 'phone'
                      | 'facebook'
                      | 'instagram'
                      | 'whatsapp'
                      | 'zalo'
                      | 'account'
                      | 'reservations'
                      | 'orders'
                      | 'vouchers'
                      | 'billing'
                      | 'notifications'
                      | 'addresses'
                      | 'invoices'
                    )
                  | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          icon?:
            | (
                | 'email'
                | 'phone'
                | 'facebook'
                | 'instagram'
                | 'whatsapp'
                | 'zalo'
                | 'account'
                | 'reservations'
                | 'orders'
                | 'vouchers'
                | 'billing'
                | 'notifications'
                | 'addresses'
                | 'invoices'
              )
            | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-text".
 */
export interface StaticText {
  id: number;
  text: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  location?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  city: string;
  slug: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  timezone:
    | 'Africa/Abidjan'
    | 'Africa/Accra'
    | 'Africa/Addis_Ababa'
    | 'Africa/Algiers'
    | 'Africa/Asmara'
    | 'Africa/Bamako'
    | 'Africa/Bangui'
    | 'Africa/Banjul'
    | 'Africa/Bissau'
    | 'Africa/Blantyre'
    | 'Africa/Brazzaville'
    | 'Africa/Bujumbura'
    | 'Africa/Cairo'
    | 'Africa/Casablanca'
    | 'Africa/Ceuta'
    | 'Africa/Conakry'
    | 'Africa/Dakar'
    | 'Africa/Dar_es_Salaam'
    | 'Africa/Djibouti'
    | 'Africa/Douala'
    | 'Africa/El_Aaiun'
    | 'Africa/Freetown'
    | 'Africa/Gaborone'
    | 'Africa/Harare'
    | 'Africa/Johannesburg'
    | 'Africa/Juba'
    | 'Africa/Kampala'
    | 'Africa/Khartoum'
    | 'Africa/Kigali'
    | 'Africa/Kinshasa'
    | 'Africa/Lagos'
    | 'Africa/Libreville'
    | 'Africa/Lome'
    | 'Africa/Luanda'
    | 'Africa/Lubumbashi'
    | 'Africa/Lusaka'
    | 'Africa/Malabo'
    | 'Africa/Maputo'
    | 'Africa/Maseru'
    | 'Africa/Mbabane'
    | 'Africa/Mogadishu'
    | 'Africa/Monrovia'
    | 'Africa/Nairobi'
    | 'Africa/Ndjamena'
    | 'Africa/Niamey'
    | 'Africa/Nouakchott'
    | 'Africa/Ouagadougou'
    | 'Africa/Porto'
    | 'Africa/Sao_Tome'
    | 'Africa/Tripoli'
    | 'Africa/Tunis'
    | 'Africa/Windhoek'
    | 'America/Adak'
    | 'America/Anchorage'
    | 'America/Anguilla'
    | 'America/Antigua'
    | 'America/Araguaina'
    | 'America/Argentina'
    | 'America/Aruba'
    | 'America/Asuncion'
    | 'America/Atikokan'
    | 'America/Bahia'
    | 'America/Bahia_Banderas'
    | 'America/Barbados'
    | 'America/Belem'
    | 'America/Belize'
    | 'America/Blanc'
    | 'America/Boa_Vista'
    | 'America/Bogota'
    | 'America/Boise'
    | 'America/Cambridge_Bay'
    | 'America/Campo_Grande'
    | 'America/Cancun'
    | 'America/Caracas'
    | 'America/Cayenne'
    | 'America/Cayman'
    | 'America/Chicago'
    | 'America/Chihuahua'
    | 'America/Ciudad_Juarez'
    | 'America/Costa_Rica'
    | 'America/Creston'
    | 'America/Cuiaba'
    | 'America/Curacao'
    | 'America/Danmarkshavn'
    | 'America/Dawson'
    | 'America/Dawson_Creek'
    | 'America/Denver'
    | 'America/Detroit'
    | 'America/Dominica'
    | 'America/Edmonton'
    | 'America/Eirunepe'
    | 'America/El_Salvador'
    | 'America/Fort_Nelson'
    | 'America/Fortaleza'
    | 'America/Glace_Bay'
    | 'America/Goose_Bay'
    | 'America/Grand_Turk'
    | 'America/Grenada'
    | 'America/Guadeloupe'
    | 'America/Guatemala'
    | 'America/Guayaquil'
    | 'America/Guyana'
    | 'America/Halifax'
    | 'America/Havana'
    | 'America/Hermosillo'
    | 'America/Indiana'
    | 'America/Inuvik'
    | 'America/Iqaluit'
    | 'America/Jamaica'
    | 'America/Juneau'
    | 'America/Kentucky'
    | 'America/Kralendijk'
    | 'America/La_Paz'
    | 'America/Lima'
    | 'America/Los_Angeles'
    | 'America/Lower_Princes'
    | 'America/Maceio'
    | 'America/Managua'
    | 'America/Manaus'
    | 'America/Marigot'
    | 'America/Martinique'
    | 'America/Matamoros'
    | 'America/Mazatlan'
    | 'America/Menominee'
    | 'America/Merida'
    | 'America/Metlakatla'
    | 'America/Mexico_City'
    | 'America/Miquelon'
    | 'America/Moncton'
    | 'America/Monterrey'
    | 'America/Montevideo'
    | 'America/Montserrat'
    | 'America/Nassau'
    | 'America/New_York'
    | 'America/Nome'
    | 'America/Noronha'
    | 'America/North_Dakota'
    | 'America/Nuuk'
    | 'America/Ojinaga'
    | 'America/Panama'
    | 'America/Paramaribo'
    | 'America/Phoenix'
    | 'America/Port'
    | 'America/Port_of_Spain'
    | 'America/Porto_Velho'
    | 'America/Puerto_Rico'
    | 'America/Punta_Arenas'
    | 'America/Rankin_Inlet'
    | 'America/Recife'
    | 'America/Regina'
    | 'America/Resolute'
    | 'America/Rio_Branco'
    | 'America/Santarem'
    | 'America/Santiago'
    | 'America/Santo_Domingo'
    | 'America/Sao_Paulo'
    | 'America/Scoresbysund'
    | 'America/Sitka'
    | 'America/St_Barthelemy'
    | 'America/St_Johns'
    | 'America/St_Kitts'
    | 'America/St_Lucia'
    | 'America/St_Thomas'
    | 'America/St_Vincent'
    | 'America/Swift_Current'
    | 'America/Tegucigalpa'
    | 'America/Thule'
    | 'America/Tijuana'
    | 'America/Toronto'
    | 'America/Tortola'
    | 'America/Vancouver'
    | 'America/Whitehorse'
    | 'America/Winnipeg'
    | 'America/Yakutat'
    | 'America/Yellowknife'
    | 'Antarctica/Casey'
    | 'Antarctica/Davis'
    | 'Antarctica/DumontDUrville'
    | 'Antarctica/Macquarie'
    | 'Antarctica/Mawson'
    | 'Antarctica/McMurdo'
    | 'Antarctica/Palmer'
    | 'Antarctica/Rothera'
    | 'Antarctica/Syowa'
    | 'Antarctica/Troll'
    | 'Antarctica/Vostok'
    | 'Arctic/Longyearbyen'
    | 'Asia/Aden'
    | 'Asia/Almaty'
    | 'Asia/Amman'
    | 'Asia/Anadyr'
    | 'Asia/Aqtau'
    | 'Asia/Aqtobe'
    | 'Asia/Ashgabat'
    | 'Asia/Atyrau'
    | 'Asia/Baghdad'
    | 'Asia/Bahrain'
    | 'Asia/Baku'
    | 'Asia/Bangkok'
    | 'Asia/Barnaul'
    | 'Asia/Beirut'
    | 'Asia/Bishkek'
    | 'Asia/Brunei'
    | 'Asia/Chita'
    | 'Asia/Choibalsan'
    | 'Asia/Colombo'
    | 'Asia/Damascus'
    | 'Asia/Dhaka'
    | 'Asia/Dili'
    | 'Asia/Dubai'
    | 'Asia/Dushanbe'
    | 'Asia/Famagusta'
    | 'Asia/Gaza'
    | 'Asia/Hebron'
    | 'Asia/Ho_Chi_Minh'
    | 'Asia/Hong_Kong'
    | 'Asia/Hovd'
    | 'Asia/Irkutsk'
    | 'Asia/Jakarta'
    | 'Asia/Jayapura'
    | 'Asia/Jerusalem'
    | 'Asia/Kabul'
    | 'Asia/Kamchatka'
    | 'Asia/Karachi'
    | 'Asia/Kathmandu'
    | 'Asia/Khandyga'
    | 'Asia/Kolkata'
    | 'Asia/Krasnoyarsk'
    | 'Asia/Kuala_Lumpur'
    | 'Asia/Kuching'
    | 'Asia/Kuwait'
    | 'Asia/Macau'
    | 'Asia/Magadan'
    | 'Asia/Makassar'
    | 'Asia/Manila'
    | 'Asia/Muscat'
    | 'Asia/Nicosia'
    | 'Asia/Novokuznetsk'
    | 'Asia/Novosibirsk'
    | 'Asia/Omsk'
    | 'Asia/Oral'
    | 'Asia/Phnom_Penh'
    | 'Asia/Pontianak'
    | 'Asia/Pyongyang'
    | 'Asia/Qatar'
    | 'Asia/Qostanay'
    | 'Asia/Qyzylorda'
    | 'Asia/Riyadh'
    | 'Asia/Sakhalin'
    | 'Asia/Samarkand'
    | 'Asia/Seoul'
    | 'Asia/Shanghai'
    | 'Asia/Singapore'
    | 'Asia/Srednekolymsk'
    | 'Asia/Taipei'
    | 'Asia/Tashkent'
    | 'Asia/Tbilisi'
    | 'Asia/Tehran'
    | 'Asia/Thimphu'
    | 'Asia/Tokyo'
    | 'Asia/Tomsk'
    | 'Asia/Ulaanbaatar'
    | 'Asia/Urumqi'
    | 'Asia/Ust'
    | 'Asia/Vientiane'
    | 'Asia/Vladivostok'
    | 'Asia/Yakutsk'
    | 'Asia/Yangon'
    | 'Asia/Yekaterinburg'
    | 'Asia/Yerevan'
    | 'Atlantic/Azores'
    | 'Atlantic/Bermuda'
    | 'Atlantic/Canary'
    | 'Atlantic/Cape_Verde'
    | 'Atlantic/Faroe'
    | 'Atlantic/Madeira'
    | 'Atlantic/Reykjavik'
    | 'Atlantic/South_Georgia'
    | 'Atlantic/St_Helena'
    | 'Atlantic/Stanley'
    | 'Australia/Adelaide'
    | 'Australia/Brisbane'
    | 'Australia/Broken_Hill'
    | 'Australia/Darwin'
    | 'Australia/Eucla'
    | 'Australia/Hobart'
    | 'Australia/Lindeman'
    | 'Australia/Lord_Howe'
    | 'Australia/Melbourne'
    | 'Australia/Perth'
    | 'Australia/Sydney'
    | 'Europe/Amsterdam'
    | 'Europe/Andorra'
    | 'Europe/Astrakhan'
    | 'Europe/Athens'
    | 'Europe/Belgrade'
    | 'Europe/Berlin'
    | 'Europe/Bratislava'
    | 'Europe/Brussels'
    | 'Europe/Bucharest'
    | 'Europe/Budapest'
    | 'Europe/Busingen'
    | 'Europe/Chisinau'
    | 'Europe/Copenhagen'
    | 'Europe/Dublin'
    | 'Europe/Gibraltar'
    | 'Europe/Guernsey'
    | 'Europe/Helsinki'
    | 'Europe/Isle_of_Man'
    | 'Europe/Istanbul'
    | 'Europe/Jersey'
    | 'Europe/Kaliningrad'
    | 'Europe/Kirov'
    | 'Europe/Kyiv'
    | 'Europe/Lisbon'
    | 'Europe/Ljubljana'
    | 'Europe/London'
    | 'Europe/Luxembourg'
    | 'Europe/Madrid'
    | 'Europe/Malta'
    | 'Europe/Mariehamn'
    | 'Europe/Minsk'
    | 'Europe/Monaco'
    | 'Europe/Moscow'
    | 'Europe/Oslo'
    | 'Europe/Paris'
    | 'Europe/Podgorica'
    | 'Europe/Prague'
    | 'Europe/Riga'
    | 'Europe/Rome'
    | 'Europe/Samara'
    | 'Europe/San_Marino'
    | 'Europe/Sarajevo'
    | 'Europe/Saratov'
    | 'Europe/Simferopol'
    | 'Europe/Skopje'
    | 'Europe/Sofia'
    | 'Europe/Stockholm'
    | 'Europe/Tallinn'
    | 'Europe/Tirane'
    | 'Europe/Ulyanovsk'
    | 'Europe/Vaduz'
    | 'Europe/Vatican'
    | 'Europe/Vienna'
    | 'Europe/Vilnius'
    | 'Europe/Volgograd'
    | 'Europe/Warsaw'
    | 'Europe/Zagreb'
    | 'Europe/Zurich'
    | 'Indian/Antananarivo'
    | 'Indian/Chagos'
    | 'Indian/Christmas'
    | 'Indian/Cocos'
    | 'Indian/Comoro'
    | 'Indian/Kerguelen'
    | 'Indian/Mahe'
    | 'Indian/Maldives'
    | 'Indian/Mauritius'
    | 'Indian/Mayotte'
    | 'Indian/Reunion'
    | 'Pacific/Apia'
    | 'Pacific/Auckland'
    | 'Pacific/Bougainville'
    | 'Pacific/Chatham'
    | 'Pacific/Chuuk'
    | 'Pacific/Easter'
    | 'Pacific/Efate'
    | 'Pacific/Fakaofo'
    | 'Pacific/Fiji'
    | 'Pacific/Funafuti'
    | 'Pacific/Galapagos'
    | 'Pacific/Gambier'
    | 'Pacific/Guadalcanal'
    | 'Pacific/Guam'
    | 'Pacific/Honolulu'
    | 'Pacific/Kanton'
    | 'Pacific/Kiritimati'
    | 'Pacific/Kosrae'
    | 'Pacific/Kwajalein'
    | 'Pacific/Majuro'
    | 'Pacific/Marquesas'
    | 'Pacific/Midway'
    | 'Pacific/Nauru'
    | 'Pacific/Niue'
    | 'Pacific/Norfolk'
    | 'Pacific/Noumea'
    | 'Pacific/Pago_Pago'
    | 'Pacific/Palau'
    | 'Pacific/Pitcairn'
    | 'Pacific/Pohnpei'
    | 'Pacific/Port_Moresby'
    | 'Pacific/Rarotonga'
    | 'Pacific/Saipan'
    | 'Pacific/Tahiti'
    | 'Pacific/Tarawa'
    | 'Pacific/Tongatapu'
    | 'Pacific/Wake'
    | 'Pacific/Wallis';
  region: number | Region;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  phone: string;
  email: string;
  description: string;
  generalHours: string;
  vendureChannel: string;
  vendureDeliveryChannel: string;
  wixLocationId?: string | null;
  address1: string;
  address2?: string | null;
  district?: string | null;
  ward?: string | null;
  city: number | City;
  google_map_url: string;
  /**
   * @minItems 2
   * @maxItems 2
   */
  coordinates?: [number, number] | null;
  hours?:
    | {
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        open: string;
        close: string;
        id?: string | null;
      }[]
    | null;
  primaryImage: number | Media;
  heroImage: number | Media;
  contentImages?: (number | Media)[] | null;
  areas?:
    | {
        name: string;
        seating?: number | null;
        description: string;
        phone?: string | null;
        email?: string | null;
        images: (number | Media)[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  cities: (number | City)[];
  overview: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  description: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  requirements: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  schedule?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  applications?: (number | CareerApplication)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications".
 */
export interface CareerApplication {
  id: number;
  name: string;
  phone: string;
  email: string;
  cv_url?: string | null;
  career?: (number | null) | Career;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  title: string;
  subtitle?: string | null;
  slug: string;
  slug_auto_slug?: boolean | null;
  regions?: (number | null) | Region;
  startDate?: string | null;
  endDate?: string | null;
  text: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  promoImage: number | Media;
  mobilePromoImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-guidebook-categories".
 */
export interface StaffGuidebookCategory {
  id: number;
  category: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  parent?: (number | null) | StaffGuidebookCategory;
  breadcrumbs?:
    | {
        doc?: (number | null) | StaffGuidebookCategory;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-guidebook-pages".
 */
export interface StaffGuidebookPage {
  id: number;
  title: string;
  slug: string;
  slug_auto_slug?: boolean | null;
  category: number | StaffGuidebookCategory;
  text?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'presets';
        value: number | Preset;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'static-text';
        value: number | StaticText;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'butcher-categories';
        value: number | ButcherCategory;
      } | null)
    | ({
        relationTo: 'product-categories';
        value: number | ProductCategory;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'career-applications';
        value: number | CareerApplication;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'staff-guidebook-categories';
        value: number | StaffGuidebookCategory;
      } | null)
    | ({
        relationTo: 'staff-guidebook-pages';
        value: number | StaffGuidebookPage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  description?: T;
  style?: T;
  content?:
    | T
    | {
        hero?:
          | T
          | {
              type?: T;
              alignment?: T;
              icon?: T;
              backgroundImage?: T;
              title?: T;
              subtitle?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          appearance?: T;
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'multi-panel-cta'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    appearance?: T;
                    backgroundImage?: T;
                    title?: T;
                    description?: T;
                  };
              panels?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    text?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                appearance?: T;
                                type?: T;
                                newTab?: T;
                                icon?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'butcher-shop-promo'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    style?: T;
                    backgroundImage?: T;
                    title?: T;
                    description?: T;
                  };
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              categories?:
                | T
                | {
                    category?: T;
                    columns?: T;
                    rows?: T;
                    image?: T;
                    id?: T;
                  };
              footer?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'product-highlights'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              categories?: T;
              id?: T;
              blockName?: T;
            };
        'social-feed'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    line1?: T;
                    line2?: T;
                  };
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'region-select-header'?:
          | T
          | {
              line1?: T;
              line2?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'locations-grid'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'cities-filter'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'discover-locations'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              style?: T;
              title?: T;
              image?: T;
              testimonies?:
                | T
                | {
                    image?: T;
                    name?: T;
                    testimony?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'page-header'?:
          | T
          | {
              title?: T;
              text?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'text-and-image'?:
          | T
          | {
              title?: T;
              text?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        'event-room-selector'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        'contact-request-form'?:
          | T
          | {
              title?: T;
              text?: T;
              type?: T;
              targetEmail?: T;
              id?: T;
              blockName?: T;
            };
        'promo-list'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        'careers-grid'?:
          | T
          | {
              style?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        carousel?:
          | T
          | {
              style?: T;
              title?: T;
              slides?:
                | T
                | {
                    image?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        specials?:
          | T
          | {
              title?: T;
              subtitle?: T;
              style?: T;
              shop?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          appearance?: T;
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        vouchers?:
          | T
          | {
              title?: T;
              description?: T;
              amount_presets?:
                | T
                | {
                    region?: T;
                    disclaimer?: T;
                    amounts?:
                      | T
                      | {
                          amount?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "presets_select".
 */
export interface PresetsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  slug_auto_slug?: T;
  description?: T;
  style?: T;
  content?:
    | T
    | {
        'store-product-details'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'location-hero'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'location-info'?:
          | T
          | {
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        'location-areas'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        'location-highlight'?:
          | T
          | {
              title?: T;
              text?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        'career-details'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'preset-hero'?:
          | T
          | {
              type?: T;
              alignment?: T;
              icon?: T;
              backgroundImage?: T;
              title?: T;
              subtitle?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          appearance?: T;
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-multi-panel-cta'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    appearance?: T;
                    backgroundImage?: T;
                    title?: T;
                    description?: T;
                  };
              panels?:
                | T
                | {
                    image?: T;
                    title?: T;
                    subtitle?: T;
                    text?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                appearance?: T;
                                type?: T;
                                newTab?: T;
                                icon?: T;
                                reference?: T;
                                url?: T;
                                label?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-butcher-shop-promo'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    style?: T;
                    backgroundImage?: T;
                    title?: T;
                    description?: T;
                  };
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              categories?:
                | T
                | {
                    category?: T;
                    columns?: T;
                    rows?: T;
                    image?: T;
                    id?: T;
                  };
              footer?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-product-highlights'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    title?: T;
                    description?: T;
                  };
              categories?: T;
              id?: T;
              blockName?: T;
            };
        'preset-social-feed'?:
          | T
          | {
              basicInfo?:
                | T
                | {
                    line1?: T;
                    line2?: T;
                  };
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              images?:
                | T
                | {
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-region-select-header'?:
          | T
          | {
              line1?: T;
              line2?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-locations-grid'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'preset-cities-filter'?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        'preset-discover-locations'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        'preset-testimonials'?:
          | T
          | {
              style?: T;
              title?: T;
              image?: T;
              testimonies?:
                | T
                | {
                    image?: T;
                    name?: T;
                    testimony?: T;
                    rating?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-page-header'?:
          | T
          | {
              title?: T;
              text?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-text-and-image'?:
          | T
          | {
              title?: T;
              text?: T;
              images?: T;
              id?: T;
              blockName?: T;
            };
        'preset-event-room-selector'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        'preset-contact-request-form'?:
          | T
          | {
              title?: T;
              text?: T;
              type?: T;
              targetEmail?: T;
              id?: T;
              blockName?: T;
            };
        'preset-promo-list'?:
          | T
          | {
              title?: T;
              id?: T;
              blockName?: T;
            };
        'preset-careers-grid'?:
          | T
          | {
              style?: T;
              title?: T;
              subtitle?: T;
              description?: T;
              bgImage?: T;
              id?: T;
              blockName?: T;
            };
        'preset-carousel'?:
          | T
          | {
              style?: T;
              title?: T;
              slides?:
                | T
                | {
                    image?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-specials'?:
          | T
          | {
              title?: T;
              subtitle?: T;
              style?: T;
              shop?: T;
              id?: T;
              blockName?: T;
            };
        'preset-cta'?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          appearance?: T;
                          type?: T;
                          newTab?: T;
                          icon?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'preset-shop'?:
          | T
          | {
              type?: T;
              id?: T;
              blockName?: T;
            };
        'preset-vouchers'?:
          | T
          | {
              title?: T;
              description?: T;
              amount_presets?:
                | T
                | {
                    region?: T;
                    disclaimer?: T;
                    amounts?:
                      | T
                      | {
                          amount?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  description?: T;
  vendure_id?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  items?:
    | T
    | {
        title?: T;
        type?: T;
        style?: T;
        colspan?: T;
        subitems?:
          | T
          | {
              title?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    icon?: T;
                    reference?: T;
                    url?: T;
                  };
              id?: T;
            };
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              icon?: T;
              reference?: T;
              url?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "static-text_select".
 */
export interface StaticTextSelect<T extends boolean = true> {
  text?: T;
  slug?: T;
  slug_auto_slug?: T;
  location?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  country_code?: T;
  currency_code?: T;
  coordinates?: T;
  defaultLocale?: T;
  availableLocales?: T;
  hostnames?: T;
  vendureChannel?: T;
  vendureDeliveryChannel?: T;
  awsMapProvider?: T;
  awsPlacesIndex?: T;
  awsLocationRegion?: T;
  awsLocationKey?: T;
  awsLocationAccessKey?: T;
  awsLocationSecret?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  city?: T;
  slug?: T;
  coordinates?: T;
  timezone?: T;
  region?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  phone?: T;
  email?: T;
  description?: T;
  generalHours?: T;
  vendureChannel?: T;
  vendureDeliveryChannel?: T;
  wixLocationId?: T;
  address1?: T;
  address2?: T;
  district?: T;
  ward?: T;
  city?: T;
  google_map_url?: T;
  coordinates?: T;
  hours?:
    | T
    | {
        day?: T;
        open?: T;
        close?: T;
        id?: T;
      };
  primaryImage?: T;
  heroImage?: T;
  contentImages?: T;
  areas?:
    | T
    | {
        name?: T;
        seating?: T;
        description?: T;
        phone?: T;
        email?: T;
        images?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "butcher-categories_select".
 */
export interface ButcherCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  vendureSlug?: T;
  defaultImage?: T;
  availableRegions?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-categories_select".
 */
export interface ProductCategoriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  vendureSlug?: T;
  parentCategory?: T;
  defaultImage?: T;
  availableRegions?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  cities?: T;
  overview?: T;
  description?: T;
  requirements?: T;
  schedule?: T;
  benefits?: T;
  applications?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career-applications_select".
 */
export interface CareerApplicationsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  cv_url?: T;
  career?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  slug?: T;
  slug_auto_slug?: T;
  regions?: T;
  startDate?: T;
  endDate?: T;
  text?: T;
  promoImage?: T;
  mobilePromoImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-guidebook-categories_select".
 */
export interface StaffGuidebookCategoriesSelect<T extends boolean = true> {
  category?: T;
  slug?: T;
  slug_auto_slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff-guidebook-pages_select".
 */
export interface StaffGuidebookPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  slug_auto_slug?: T;
  category?: T;
  text?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}